packageName: "github.com/example/todo"
generate:
  schemaName: "public"
  postgres:
  - modelName: "Todo"
    modelStruct: "todo.Row"
    modelPackage: "github.com/example/todo/models"
    postgresName: "Todo"
    primaryKey: "TodoID"
    primaryKeyType: "int"
  - modelName: "Session"
    modelStruct: "session.Row"
    modelPackage: "github.com/example/todo/models"
    postgresName: "Session"
    primaryKey: "SessionID"
    primaryKeyType: "uuid.UUID"
  - modelName: "User"
    modelStruct: "user.Row"
    modelPackage: "github.com/example/todo/models"
    postgresName: "User"
    primaryKey: "UserID"
    primaryKeyType: "int"
  resolvers:
  - singularName: "Todo"
    pluralName: "Todos"
    primaryKey: "TodoID" # Defaults to 'ID'
    primaryKeyType: "int" # Defaults to 'string'
    query: true
